language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
- sudo add-apt-repository ppa:marutter/rdev -y
- sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8 r-base
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  - export CXX="g++-4.8"
  - CC="gcc-4.8"

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
