os:
  - linux

language: cpp
compiler: g++

before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
sudo apt-get update && sudo apt-get install -qq g++-4.8 && export CXX="g++-4.8" && CC="gcc-4.8"; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

